In [44]:
import pandas as pd  # keywords are highlighted in green, other strings in red, etc.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
file= pd.read_csv('fifa21_train.csv')

In [46]:
data1=file._get_numeric_data() #numerical
data2=file.select_dtypes(include=['object']) #whih columns are categorical
data2['ID']=data1['ID']
display(data1.head()) 
display(data2.head())

,ID,Age,Growth,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,184383,26,1,258,54,47,43,70,44.0,286,...,6,1682,357,69,51,63,63,51,60,64
1,188044,30,0,365,66,79,76,68,76.0,375,...,16,1961,412,83,75,68,82,33,71,77
2,184431,33,0,336,73,76,34,78,75.0,424,...,3,1925,404,80,77,78,86,27,56,80
3,233796,22,13,242,44,42,58,62,36.0,259,...,12,1527,329,57,44,54,57,57,60,59
4,234799,23,8,249,49,37,61,68,34.0,280,...,15,1664,360,66,44,60,64,60,66,65

,Name,Nationality,Club,BP,Position,Team & Contract,Height,Weight,foot,Joined,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,ID
0,A. Pasche,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,"Jul 1, 2015",...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,184383
1,Alan Carvalho,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,"Jan 16, 2015",...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,188044
2,S. Giovinco,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,"Jan 31, 2019",...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,184431
3,J. Evans,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,"Jul 1, 2016",...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,233796
4,Y. Demoncy,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,"Jul 1, 2018",...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,234799

In [82]:
# Delete rows containing either 3% NaN Values
perc = 3.0 
min_count =  int(((100-perc)/100)*data1.shape[1] + 1)
mod_df = data1.dropna( axis=0, 
                    thresh=min_count)
mod_df.shape

(11660, 53)

In [48]:
#drop columns with values nan more than 75%
perc = 75 
min_count =  int(((100-perc)/100)*mod_df.shape[1] + 1)
mod_df_num = mod_df.dropna( axis=1, 
                    thresh=min_count)

print(mod_df_num.shape, mod_df.shape)
#print(mod_df_num)

(11660, 53) (11660, 53)

In [49]:
# 
perc = 75.0 
min_count =  int(((100-perc)/100)*data2.shape[1] + 1)
mod_df_str = data2.dropna( axis=1, 
                    thresh=min_count)
mod_df_str.shape

(11701, 49)

In [50]:
good_data=mod_df_num.merge(mod_df_str, how = 'inner', on=['ID'] ) #there are in both frames, ID is the same in both

In [51]:
def clean_Hits(x):
    if type(x) is str:
        if x.find('K'):
            s = x.replace('K', '000')
            s=  x.replace('.', '')
            
        return float(s[0])
        
    else:
        return float(x)
  
df_test=data2['Hits'].apply(clean_Hits)
print(df_test)

0        3.0
1        4.0
2        7.0
3        7.0
4        4.0
        ...
11696    3.0
11697    3.0
11698    6.0
11699    3.0
11700    8.0
Name: Hits, Length: 11701, dtype: float64

In [52]:
#df2['Team & Contract']= df['Team & Contract']
#df2["Club Contract"] = df2['Club'].astype(str) +" "+ df2["Contract"]
#print(df2['Club Contract'])
#df2['Club Contract']==df2['Team & Contract']

In [53]:
#Height: 
def clean_height(x):
    if type(x) is str:
        s = x.replace('"', '')
        s=  int(s.split("'")[0])*30.48 + int(s.split("'")[1])*2.54
        return s
        
    else:
        return x
  
df_test=data2['Height'].apply(clean_height)
print(df_test)

0        175.26
1        182.88
2        162.56
3        177.80
4        180.34
          ...
11696    185.42
11697    185.42
11698    167.64
11699    187.96
11700    170.18
Name: Height, Length: 11701, dtype: float64

In [54]:
def clean_stars(x):
    if type(x) is str:
        if x.find(' ★') or x.find ('★'):
            s = x.replace(' ★', '') 
            s = x.replace('★', '')
           
            s = float(s)
        return s
        
    else:
        return x
df_test=data2['IR'].apply(clean_stars)
print(df_test)

0        1.0
1        2.0
2        2.0
3        1.0
4        1.0
        ...
11696    1.0
11697    1.0
11698    1.0
11699    3.0
11700    1.0
Name: IR, Length: 11701, dtype: float64

In [55]:
# Function fix plis minus problem

def clean_plus_minus(x):
    if type(x) is str:
        if x.find('+-') or x.find('+'):
            s = x.split('+')
            return float(s[0])
        elif x.find('-'):
            s = x.split('-')
            return float(s[0])
    else:
        return x

df_test=data2['CDM'].apply(clean_plus_minus)

print(df_test)

0        59.0
1        53.0
2        56.0
3        58.0
4        64.0
         ...
11696    60.0
11697    26.0
11698    44.0
11699    68.0
11700    43.0
Name: CDM, Length: 11701, dtype: float64

In [56]:
def clean_wage(x):
    if type(x) is str:

        s = x.replace('€', '').replace('K', '000')

        return float(s)
        
    else:
        return x
  
df_test=data2['Wage'].apply(clean_wage)
print(df_test)

0         4000.0
1        23000.0
2        49000.0
3         4000.0
4         2000.0
          ...
11696     3000.0
11697     4000.0
11698     2000.0
11699        0.0
11700     2000.0
Name: Wage, Length: 11701, dtype: float64

In [57]:
#Weight fixed

def clean_weight(x):
    if type(x) is str:
        if x.find('lbs'):
            s = x.replace('lbs', '')
            s = float(s)*  0.45359237
        return s
        
    else:
        return x
  
df_test=data2['Weight'].apply(clean_weight)
print(df_test)

0        73.028372
1        72.121187
2        60.781378
3        68.946040
4        68.038855
           ...
11696    76.203518
11697    78.925072
11698    64.863709
11699    81.193034
11700    64.863709
Name: Weight, Length: 11701, dtype: float64

In [58]:
def clean_value(x):
    if type(x) is str:
        s = x.replace('€', '').replace('K', "000").replace('M', '000000').translate({ord('.'): None})
        
        return float(s)
        
    else:
        return x
  
df_test=data2['Release Clause'].apply(clean_value)

print(df_test)

0           801000.0
1                0.0
2        153000000.0
3           694000.0
4         14000000.0
            ...
11696       891000.0
11697     29000000.0
11698     17000000.0
11699            0.0
11700     12000000.0
Name: Release Clause, Length: 11701, dtype: float64

In [59]:

def clean_dataset(df):
    df2 = df.copy()
    df2['Weight'] = df2['Weight'].apply(clean_weight)
    df2['Value'] = df2['Value'].apply(clean_value)
    df2['Wage'] = df2['Wage'].apply(clean_wage)
    df2['Release Clause'] = df2['Release Clause'].apply(clean_value)
    df2['W/F'] = df2['W/F'].apply(clean_stars)
    df2['Height'] = df2['Height'].apply(clean_height)
    df2['Hits'] = df2['Hits'].apply(clean_Hits)
    df2['SM'] = df2['SM'].apply(clean_stars)
    df2['IR'] = df2['IR'].apply(clean_stars)
    df2['RB']=df2['RB'].apply(clean_plus_minus)
    df2['GK']= df2['GK'].apply(clean_plus_minus)
    df2['RWB'] = df2['RWB'].apply(clean_plus_minus)
    df2['RDM'] = df2['RDM'].apply(clean_plus_minus)
    df2['LCB']=df2['LCB'].apply(clean_plus_minus)
    df2['RCB']=df2['RCB'].apply(clean_plus_minus)
    df2['RB']=df2['RB'].apply(clean_plus_minus)
    df2['GK']=df2['GK'].apply(clean_plus_minus)
    df2['LB'] = df2['LB'].apply(clean_plus_minus)
    df2['CB'] = df2['CB'].apply(clean_plus_minus)
    df2['RCB'] = df2['RCB'].apply(clean_plus_minus)
    df2['CDM'] = df2['CDM'].apply(clean_plus_minus)
    df2['LDM'] = df2['LDM'].apply(clean_plus_minus)
    #
    df2['LS']=df2['LS'].apply(clean_plus_minus)
    df2['ST']=df2['ST'].apply(clean_plus_minus)
    df2['RS'] = df2['RS'].apply(clean_plus_minus)
    df2['LW'] = df2['LW'].apply(clean_plus_minus)
    df2['LF'] = df2['LF'].apply(clean_plus_minus)
    df2['LAM'] = df2['LAM'].apply(clean_plus_minus)
    df2['CAM'] = df2['CAM'].apply(clean_plus_minus)
    df2['RAM'] = df2['RAM'].apply(clean_plus_minus)
    df2['LM'] = df2['LM'].apply(clean_plus_minus)
    df2['LCM'] = df2['LCM'].apply(clean_plus_minus)
    df2['CM'] = df2['CM'].apply(clean_plus_minus)
    
    df2['LWB']=df2['LWB'].apply(clean_plus_minus)
    df2['CF']=df2['CF'].apply(clean_plus_minus)
    df2['RF'] = df2['RF'].apply(clean_plus_minus)
    df2['RCM'] = df2['RCM'].apply(clean_plus_minus)
    df2['RM'] = df2['RM'].apply(clean_plus_minus)
    df2['LWB'] = df2['LWB'].apply(clean_plus_minus)
    df2['RW'] = df2['RW'].apply(clean_plus_minus)
    
   
    
    return df2
print(clean_dataset(good_data))
final_data=clean_dataset(good_data)

           ID  Age  Growth  Attacking  Crossing  Finishing  Heading Accuracy  \
0      184383   26       1        258        54         47                43
1      188044   30       0        365        66         79                76
2      184431   33       0        336        73         76                34
3      233796   22      13        242        44         42                58
4      234799   23       8        249        49         37                61
...       ...  ...     ...        ...       ...        ...               ...
11655  196848   29       0        290        36         72                65
11656  232504   25       5        224        62         24                51
11657  214680   27       4         84        12         14                13
11658  221489   22       8        286        64         66                51
11659  236507   22       9        289        43         64                65

       Short Passing  Volleys  Skill  ...   LDM   CDM   RDM   RWB    LB   LCB  \
0                 70     44.0    286  ...  59.0  59.0  59.0  59.0  58.0  54.0
1                 68     76.0    375  ...  53.0  53.0  53.0  57.0  53.0  48.0
2                 78     75.0    424  ...  56.0  56.0  56.0  59.0  53.0  41.0
3                 62     36.0    259  ...  58.0  58.0  58.0  56.0  57.0  58.0
4                 68     34.0    280  ...  64.0  64.0  64.0  64.0  63.0  61.0
...              ...      ...    ...  ...   ...   ...   ...   ...   ...   ...
11655             57     60.0    283  ...  45.0  45.0  45.0  46.0  44.0  43.0
11656             59     28.0    248  ...  60.0  60.0  60.0  63.0  63.0  61.0
11657             29     16.0     96  ...  26.0  26.0  26.0  25.0  24.0  26.0
11658             64     41.0    291  ...  44.0  44.0  44.0  49.0  45.0  35.0
11659             64     53.0    267  ...  43.0  43.0  43.0  46.0  44.0  36.0

         CB   RCB    RB    GK
0      54.0  54.0  58.0  15.0
1      48.0  48.0  53.0  18.0
2      41.0  41.0  53.0  12.0
3      58.0  58.0  57.0  14.0
4      61.0  61.0  63.0  15.0
...     ...   ...   ...   ...
11655  43.0  43.0  44.0  19.0
11656  61.0  61.0  63.0  16.0
11657  26.0  26.0  24.0  69.0
11658  35.0  35.0  45.0  17.0
11659  36.0  36.0  44.0  15.0

[11660 rows x 101 columns]

In [60]:
categoricals=final_data.select_dtypes(include=[np.object])
print(categoricals)

                Name  Nationality                        Club   BP   Position  \
0          A. Pasche  Switzerland           FC Lausanne-Sport   CM     CM CDM
1      Alan Carvalho     China PR     Beijing Sinobo Guoan FC   ST   ST LW LM
2        S. Giovinco        Italy                    Al Hilal  CAM     CAM CF
3           J. Evans        Wales                Swansea City  CDM     CDM CM
4         Y. Demoncy       France  US Orléans Loiret Football  CDM     CDM CM
...              ...          ...                         ...  ...        ...
11655       I. Ávila         Peru                  Melgar FBC   ST         ST
11656  B. Böðvarsson      Iceland       Jagiellonia Białystok   LB         LB
11657      G. Gallon       France                ESTAC Troyes   GK         GK
11658      J. Flores        Chile              CD Antofagasta   RM  LM CAM RM
11659    T. Conechny    Argentina            Portland Timbers  CAM  ST CAM LM

                                    Team & Contract   foot        Joined  \
0                     FC Lausanne-Sport 2015 ~ 2020  Right   Jul 1, 2015
1      Beijing Sinobo Guoan FC Dec 31, 2020 On Loan  Right  Jan 16, 2015
2                              Al Hilal 2019 ~ 2022  Right  Jan 31, 2019
3                          Swansea City 2016 ~ 2021  Right   Jul 1, 2016
4            US Orléans Loiret Football 2018 ~ 2021  Right   Jul 1, 2018
...                                             ...    ...           ...
11655                        Melgar FBC 2019 ~ 2021  Right   Jul 1, 2019
11656             Jagiellonia Białystok 2018 ~ 2021   Left   Feb 8, 2018
11657                      ESTAC Troyes 2019 ~ 2022  Right   Jul 1, 2019
11658                    CD Antofagasta 2019 ~ 2024  Right  Jan 23, 2019
11659                  Portland Timbers 2019 ~ 2020   Left  Jul 22, 2019

      Loan Date End              Contract     A/W     D/W
0               NaN           2015 ~ 2020    High  Medium
1      Dec 31, 2020  Dec 31, 2020 On Loan    High     Low
2               NaN           2019 ~ 2022    High  Medium
3               NaN           2016 ~ 2021  Medium  Medium
4               NaN           2018 ~ 2021     Low  Medium
...             ...                   ...     ...     ...
11655           NaN           2019 ~ 2021    High     Low
11656           NaN           2018 ~ 2021  Medium  Medium
11657           NaN           2019 ~ 2022  Medium  Medium
11658           NaN           2019 ~ 2024    High  Medium
11659           NaN           2019 ~ 2020    High     Low

[11660 rows x 12 columns]

C:\Users\tanya\AppData\Local\Temp\ipykernel_40220\2878955692.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  categoricals=final_data.select_dtypes(include=[np.object])

In [61]:
numerical=final_data.select_dtypes(include=[np.number])
#print(numerical)
final_data.select_dtypes(include=[np.number])
y = numerical['OVA']

In [62]:
#numerical.corr().head(50)
numerical[numerical.columns[1:]].corr()['OVA'][:]
#numerical[numerical.columns[1:]].corr()['OVA'][:].head(50)
#numerical[numerical.columns[1:]].corr()['OVA'][:].tail(50)
numerical = numerical.loc[:,~numerical.columns.duplicated()].copy() #dropping the duplicates
numerical.shape

(11660, 89)

In [63]:
numerical.columns.get_loc("OVA")

52

In [40]:
def correlation(dataset, threshold):
    col_corr = set() # Set of all the names of deleted columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        
        if (corr_matrix.iloc[i, numerical.columns.get_loc("OVA")] >= threshold) and (corr_matrix.columns[numerical.columns.get_loc("OVA")] not in col_corr):
            colname = corr_matrix.columns[i] # getting the name of column
            col_corr.add(colname)
            if colname in dataset.columns:
                del dataset[colname] # deleting the column from the dataset

    
    print(dataset)

In [64]:
non = correlation(numerical, 0.75)

           ID  Age  Growth  Attacking  Crossing  Finishing  Heading Accuracy  \
0      184383   26       1        258        54         47                43
1      188044   30       0        365        66         79                76
2      184431   33       0        336        73         76                34
3      233796   22      13        242        44         42                58
4      234799   23       8        249        49         37                61
...       ...  ...     ...        ...       ...        ...               ...
11655  196848   29       0        290        36         72                65
11656  232504   25       5        224        62         24                51
11657  214680   27       4         84        12         14                13
11658  221489   22       8        286        64         66                51
11659  236507   22       9        289        43         64                65

       Short Passing  Volleys  Skill  ...   LDM   CDM   RDM   RWB    LB   LCB  \
0                 70     44.0    286  ...  59.0  59.0  59.0  59.0  58.0  54.0
1                 68     76.0    375  ...  53.0  53.0  53.0  57.0  53.0  48.0
2                 78     75.0    424  ...  56.0  56.0  56.0  59.0  53.0  41.0
3                 62     36.0    259  ...  58.0  58.0  58.0  56.0  57.0  58.0
4                 68     34.0    280  ...  64.0  64.0  64.0  64.0  63.0  61.0
...              ...      ...    ...  ...   ...   ...   ...   ...   ...   ...
11655             57     60.0    283  ...  45.0  45.0  45.0  46.0  44.0  43.0
11656             59     28.0    248  ...  60.0  60.0  60.0  63.0  63.0  61.0
11657             29     16.0     96  ...  26.0  26.0  26.0  25.0  24.0  26.0
11658             64     41.0    291  ...  44.0  44.0  44.0  49.0  45.0  35.0
11659             64     53.0    267  ...  43.0  43.0  43.0  46.0  44.0  36.0

         CB   RCB    RB    GK
0      54.0  54.0  58.0  15.0
1      48.0  48.0  53.0  18.0
2      41.0  41.0  53.0  12.0
3      58.0  58.0  57.0  14.0
4      61.0  61.0  63.0  15.0
...     ...   ...   ...   ...
11655  43.0  43.0  44.0  19.0
11656  61.0  61.0  63.0  16.0
11657  26.0  26.0  24.0  69.0
11658  35.0  35.0  45.0  17.0
11659  36.0  36.0  44.0  15.0

[11660 rows x 83 columns]

In [65]:
X=numerical

In [72]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler()
MinMaxtransformer.fit(X) # fit() Determine the min and the max of each column
x_normalized = MinMaxtransformer.transform(X) # .transform() applies the transformation x_normalized will be np.array
print("The type of x_normalized is {} and the shape of the array is {}".format(type(x_normalized),x_normalized.shape))
x_normalized = pd.DataFrame(x_normalized,columns=X.columns) # Take the column's names from X_num
x_normalized.head()

The type of x_normalized is <class 'numpy.ndarray'> and the shape of the array is (11660, 83)

,ID,Age,Growth,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
0,0.711626,0.370370,0.038462,0.546835,0.545455,0.478261,0.431818,0.710843,0.465116,0.569087,...,0.614286,0.614286,0.614286,0.642857,0.637681,0.527778,0.527778,0.527778,0.637681,0.075949
1,0.725758,0.518519,0.000000,0.817722,0.681818,0.826087,0.806818,0.686747,0.837209,0.777518,...,0.528571,0.528571,0.528571,0.614286,0.565217,0.444444,0.444444,0.444444,0.565217,0.113924
2,0.711811,0.629630,0.000000,0.744304,0.761364,0.793478,0.329545,0.807229,0.825581,0.892272,...,0.571429,0.571429,0.571429,0.642857,0.565217,0.347222,0.347222,0.347222,0.565217,0.037975
3,0.902364,0.222222,0.500000,0.506329,0.431818,0.423913,0.602273,0.614458,0.372093,0.505855,...,0.600000,0.600000,0.600000,0.600000,0.623188,0.583333,0.583333,0.583333,0.623188,0.063291
4,0.906235,0.259259,0.307692,0.524051,0.488636,0.369565,0.636364,0.686747,0.348837,0.555035,...,0.685714,0.685714,0.685714,0.714286,0.710145,0.625000,0.625000,0.625000,0.710145,0.075949

In [78]:
x_normalized.isna().sum().sum()

238

In [86]:
x_normalized.replace(np.nan,0)

,ID,Age,Growth,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
0,0.711626,0.370370,0.038462,0.546835,0.545455,0.478261,0.431818,0.710843,0.465116,0.569087,...,0.614286,0.614286,0.614286,0.642857,0.637681,0.527778,0.527778,0.527778,0.637681,0.075949
1,0.725758,0.518519,0.000000,0.817722,0.681818,0.826087,0.806818,0.686747,0.837209,0.777518,...,0.528571,0.528571,0.528571,0.614286,0.565217,0.444444,0.444444,0.444444,0.565217,0.113924
2,0.711811,0.629630,0.000000,0.744304,0.761364,0.793478,0.329545,0.807229,0.825581,0.892272,...,0.571429,0.571429,0.571429,0.642857,0.565217,0.347222,0.347222,0.347222,0.565217,0.037975
3,0.902364,0.222222,0.500000,0.506329,0.431818,0.423913,0.602273,0.614458,0.372093,0.505855,...,0.600000,0.600000,0.600000,0.600000,0.623188,0.583333,0.583333,0.583333,0.623188,0.063291
4,0.906235,0.259259,0.307692,0.524051,0.488636,0.369565,0.636364,0.686747,0.348837,0.555035,...,0.685714,0.685714,0.685714,0.714286,0.710145,0.625000,0.625000,0.625000,0.710145,0.075949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11655,0.759742,0.481481,0.000000,0.627848,0.340909,0.750000,0.681818,0.554217,0.651163,0.562061,...,0.414286,0.414286,0.414286,0.457143,0.434783,0.375000,0.375000,0.375000,0.434783,0.126582
11656,0.897376,0.333333,0.192308,0.460759,0.636364,0.228261,0.522727,0.578313,0.279070,0.480094,...,0.628571,0.628571,0.628571,0.700000,0.710145,0.625000,0.625000,0.625000,0.710145,0.088608
11657,0.828575,0.407407,0.153846,0.106329,0.068182,0.119565,0.090909,0.216867,0.139535,0.124122,...,0.142857,0.142857,0.142857,0.157143,0.144928,0.138889,0.138889,0.138889,0.144928,0.759494
11658,0.854858,0.222222,0.307692,0.617722,0.659091,0.684783,0.522727,0.638554,0.430233,0.580796,...,0.400000,0.400000,0.400000,0.500000,0.449275,0.263889,0.263889,0.263889,0.449275,0.101266
11659,0.912828,0.222222,0.346154,0.625316,0.420455,0.663043,0.681818,0.638554,0.569767,0.524590,...,0.385714,0.385714,0.385714,0.457143,0.434783,0.277778,0.277778,0.277778,0.434783,0.075949

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_normalized, y, test_size=0.25, random_state=42)

In [88]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8745, 83)
(2915, 83)
(8745,)
(2915,)

In [89]:

from sklearn.linear_model import LinearRegression
lm = LinearRegression()

lm.fit(X_train,y_train)


print(lm.score(X_train,y_train))
y_pred2 = lm.predict(X_train)
print(mean_squared_error(y_pred2,y_train))

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [90]:
lm.coef_

AttributeError: 'LinearRegression' object has no attribute 'coef_'